services:
  movies-service:
    container_name: movies-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production.local
    ports:
      - "50053:50053"
    networks:
      - kirt08

networks:
  kirt08:
    external: True