"""rating_age change nulluble

Revision ID: 54d4009ecc2b
Revises: 043ea7b6d32e
Create Date: 2026-03-08 20:45:48.445552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d4009ecc2b'
down_revision: Union[str, Sequence[str], None] = '043ea7b6d32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'rating_age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'rating_age',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
