"""fixes in table movies

Revision ID: aabe28f7f429
Revises: 1be4aa923259
Create Date: 2026-03-08 20:29:12.687166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aabe28f7f429'
down_revision: Union[str, Sequence[str], None] = '1be4aa923259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_year', sa.Integer(), nullable=False))
    op.add_column('movies', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.add_column('movies', sa.Column('country', sa.String(length=256), nullable=False))
    op.add_column('movies', sa.Column('rating_age', sa.Integer(), nullable=False))
    op.add_column('movies', sa.Column('category', sa.String(length=256), nullable=False))
    op.drop_constraint(op.f('movies_category_id_fkey'), 'movies', type_='foreignkey')
    op.create_foreign_key(None, 'movies', 'categories', ['category'], ['slug'])
    op.drop_column('movies', 'releaseYear')
    op.drop_column('movies', 'releaseDate')
    op.drop_column('movies', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('movies', sa.Column('releaseDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('releaseYear', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.create_foreign_key(op.f('movies_category_id_fkey'), 'movies', 'categories', ['category_id'], ['id'])
    op.drop_column('movies', 'category')
    op.drop_column('movies', 'rating_age')
    op.drop_column('movies', 'country')
    op.drop_column('movies', 'release_date')
    op.drop_column('movies', 'release_year')
    # ### end Alembic commands ###
